name: Snyk Security Quality Gates

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

jobs:
  security-quality-gates:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Snyk CLI
      uses: snyk/actions/setup@master
      
    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}
      
    - name: Run Snyk Code Test (SAST)
      run: snyk code test --severity-threshold=high --fail-on=all
      
    - name: Run Snyk SCA Test
      run: snyk test --severity-threshold=high --fail-on=all
      
    - name: Quality Gate Summary
      if: always()
      run: |
        echo "## 🚦 Security Quality Gates" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**SCA Quality Gate:** 0 high/critical severity issues" >> $GITHUB_STEP_SUMMARY
        echo "**SAST Quality Gate:** 0 high severity issues" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "All quality gates must pass before this PR can be merged." >> $GITHUB_STEP_SUMMARY
